version: '3.7'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: "true"
    volumes:
    - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
    - "8081:8081"
    restart: "always"

volumes:
  telegram-bot-api-data:
